# Generated by Django 5.0.6 on 2025-05-05 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_libro_descripcion_libro_editorial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='oferta',
            field=models.BooleanField(default=False),
        ),
    ]
