# Generated by Django 5.0.6 on 2025-05-05 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_libro_oferta'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='precio_oferta',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
